title: portal user configurations
type: object
description: 'Contains portal user settings in the "configs" field.'
x-examples:
  example-1:
    isMaster: false
    products: []
    canImpersonate: all
    status: suspended
    impersonateRegions: []
    impersonateExceptions: []
properties:
  isMaster:
    type: boolean
    default: false
    description: Indicates whether or not this portal user has full access to all subscribed products.
  products:
    type: array
    enum:
      - ECP
      - CDN
    description: 'List of products that the user has access to. The default is no products. You can specify "CDN" to represent the CDN360 product or "ECP" for the Edge Computing Platform product.'
    items:
      type: string
  canImpersonate:
    type: string
    default: all
    description: 'This setting applies to resellers only. It indicates whether the user can impersonate child customers or not. A value of "all" means the user can impersonate all child customers. A value of "none" means the user cannot impersonate any. This field works in conjunction with the <i>impersonateExceptions</i> field.'
    enum:
      - all
      - none
  status:
    type: string
    default: suspended
    description: "Indicates the status of the portal user account. An 'active' user has full access to the portal. A 'suspended' user cannot log in.  A 'pending' user is one that has been invited to use the portal but has not completed setting up the account.  You cannot call the <a href=\"#operation/createContact\">Create a  portal user</a> or <a href=\"#operation/patch-ngadmin-contacts-id\">Update a portal user</a> APIs with a status value of 'pending'."
    enum:
      - active
      - suspended
      - pending
  impersonateExceptions:
    type: array
    description: 'This setting applies to resellers only.  It contains a list of customer IDs which are exceptions to the rule defined by the <i>canImpersonate</i> field. For example, if <i>canImpersonate</i> is "all" the portal user can impersonate all child customers of the reseller. Entering one or more customer IDs as exceptions will prevent the user from impersonating those particular child customers. Conversely, if <i>canImpersonate</i> is "none", entries in the exception list represent customers who can be impersonated by this user.'
    items:
      type: integer
